orders/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("create/", views.OrderCreationAPIView.as_view()),
    path("add-item/", views.OrderItemCreationAPIView.as_view()),
    path("remove-item/<int:pk>/", views.OrderItemDeletionAPIView.as_view()),
    path("delete/<int:pk>/", views.OrderDeletionAPIView.as_view()),
    path("update/<int:pk>/", views.OrderUpdateAPIView.as_view()),
    path("list/", views.OrderListingAPIView.as_view()),
    path("supportticket/list-or-create/", views.SupportTicketListCreateAPIView.as_view()),
    path("supportticket/update-or-delete/<int:pk>/", views.SupportTicketUpdateDestroyAPIView.as_view()),
    path("filtered-listing/", views.OrderListingByStatusAPIView.as_view())
    ]

orders/urls.py
from django.urls import path

from . import views
app_name = "orders"
urlpatterns = [
    path("add-to-cart/<int:product_id>/", views.AddToCart.as_view(), name="add_to_cart"),
    path("delete-from-cart/<int:pk>/", views.DeleteProductFromCart.as_view(), name="delete_product_from_cart"),
    path("create-support-ticket/<int:order_id>/", views.CreateSupportTicket.as_view(), name="create_support_ticket"),
    path("show-cart/", views.ShowCart.as_view(), name="show_cart"),
    path("show-orders/", views.ShowOrders.as_view(), name="show_orders"),
    path("show-ticket-form/<int:pk>/", views.ShowTicketForm.as_view(), name="show_ticket_form"),
    path("list-support-tickets/", views.ListSupportTickets.as_view(), name="list_support_tickets"),
    path("finalize-order/<int:order_id>", views.FinalizeOrder.as_view(), name="finalize_order"),
]

priceoyeclone/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from priceoyeclone import settings
from products.views import Homepage


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("users/", include("users.urls")),
                  path("api/user/", include("users.api.urls")),
                  path("api/order/", include("orders.api.urls")),
                  path("api/product/", include("products.api.urls")),
                  path("products/", include("products.urls")),
                  path("orders/", include("orders.urls", namespace="orders")),
                  path("sentry-debug/", trigger_error),
                  path("", Homepage.as_view()),
                  path("gettoken/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
                  path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
                  path("token/verify/", TokenVerifyView.as_view(), name="token_refresh"),
              ] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password-reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete")
]

orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django_extensions.db.models import TimeStampedModel, ActivatorModel

from products.models import Product
from .managers import OrderManager
from .status_choices import OrderStatusChoices, SupportTicketStatusChoices

User = get_user_model()


class Order(TimeStampedModel, ActivatorModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_status = models.CharField(
        max_length=20,
        choices=OrderStatusChoices.choices,
        default=OrderStatusChoices.IN_CART
    )

    @property
    def total_price(self):
        return sum(item.price for item in self.items.all())

    def __str__(self):
        return self.user.email + ' - ' + str(self.id)

    object = OrderManager()


class OrderItem(TimeStampedModel):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    @property
    def price(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.name + " - " + str(self.id)


class SupportTicket(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(
        max_length=20,
        choices=SupportTicketStatusChoices.choices,
        default=SupportTicketStatusChoices.OPEN
    )

    def __str__(self):
        return self.title + " " + str(self.id)

orders/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import generics
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView

from orders.api.serializers import OrderSerializer, OrderItemSerializer, SupportTicketSerializer
from orders.models import OrderItem, Order, SupportTicket
from orders.status_choices import OrderStatusChoices
from products.api.permissions import IsStaff
from .filters import OrderFilter
from .permissions import IsOwner, IsOrderOwner


class OrderCreationAPIView(generics.CreateAPIView):
    serializer_class = OrderSerializer


class OrderItemCreationAPIView(generics.CreateAPIView):
    serializer_class = OrderItemSerializer


class OrderItemDeletionAPIView(generics.DestroyAPIView):
    queryset = OrderItem.objects.all()
    serializer_class = OrderItemSerializer
    permission_classes = (IsOwner,)


class OrderDeletionAPIView(generics.DestroyAPIView):
    serializer_class = OrderSerializer
    permission_classes = (IsOrderOwner,)

    def get_queryset(self):
        return Order.objects.filter(
            order_status__in=[OrderStatusChoices.ORDER_PLACED, OrderStatusChoices.IN_CART]
        )


class OrderUpdateAPIView(generics.UpdateAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    permission_classes = (IsStaff,)


class OrderListingByStatusAPIView(generics.ListAPIView):
    queryset = Order.objects.all()
    filter_backends = [DjangoFilterBackend]
    filterset_class = OrderFilter
    serializer_class = OrderSerializer
    permission_classes = (IsStaff,)



class OrderListingAPIView(generics.ListAPIView):
    serializer_class = OrderSerializer

    def get_queryset(self):
        return Order.objects.active().filter(user=self.request.user)


class SupportTicketListCreateAPIView(ListCreateAPIView):
    serializer_class = SupportTicketSerializer

    def get_queryset(self):
        return SupportTicket.objects.filter(user=self.request.user)


class SupportTicketUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = SupportTicketSerializer

    def get_queryset(self):
        return SupportTicket.objects.filter(user=self.request.user)

orders/views.py
from django.db.models import F
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic.list import ListView

from orders.models import Order, OrderItem, SupportTicket
from products.models import Product
from .status_choices import OrderStatusChoices


class FinalizeOrder(View):
    def post(self, request, *args, **kwargs):
        order_id = kwargs["order_id"]
        Order.objects.filter(id=order_id).update(
            order_status=OrderStatusChoices.ORDER_PLACED
        )
        return redirect("orders:show_orders")


class AddToCart(View):
    def get(self, request, *args, **kwargs):
        current_user = request.user
        product_id = self.kwargs["product_id"]
        product = Product.objects.get(id=product_id)
        order, created = Order.objects.get_or_create(
            user=current_user,
            order_status=OrderStatusChoices.IN_CART
        )
        order_item, order_item_created = OrderItem.objects.get_or_create(order=order, product=product)

        if not order_item_created:
            OrderItem.objects.filter(order=order, product=product).update(
                quantity=F("quantity") + 1,
                price=F("price") + product.price
            )
        else:
            OrderItem.objects.filter(order=order, product=product).update(
                price=product.price
            )

        return redirect("orders:show_cart")


class DeleteProductFromCart(DeleteView):
    model = OrderItem
    template_name = "orderitem_confirm_delete.html"
    success_url = reverse_lazy("orders:show_cart")


class ShowOrders(ListView):
    model = Order
    template_name = "show_orders.html"
    context_object_name = "orders"

    def get_queryset(self, queryset=None):
        return Order.objects.filter(user=self.request.user, order_status=OrderStatusChoices.ORDER_PLACED)


class ShowCart(DetailView):
    model = Order
    template_name = "show_cart.html"
    context_object_name = "order"

    def get_object(self, queryset=None):
        order = get_object_or_404(Order, user=self.request.user, order_status=OrderStatusChoices.IN_CART)
        return order


class ShowTicketForm(DetailView):
    model = Order
    template_name = "support_ticket_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["order_id"] = self.kwargs["pk"]
        return context


class ListSupportTickets(ListView):
    model = SupportTicket
    template_name = "list_support_tickets.html"
    context_object_name = "support_tickets"

    def get_queryset(self):
        support_tickets = SupportTicket.objects.filter(user=self.request.user)
        return support_tickets


class CreateSupportTicket(CreateView):
    model = SupportTicket
    template_name = "support_ticket_form.html"

    def post(self, request, *args, **kwargs):
        order_id = self.kwargs["order_id"]
        user = request.user
        order = get_object_or_404(Order, id=order_id, user=user)
        subject = request.POST["subject"]
        description = request.POST["description"]

        SupportTicket.objects.get_or_create(user=user,
                                            order=order,
                                            title=subject,
                                            description=description)

        return redirect("orders:list_support_tickets")

orders/templates/list_support_tickets.html
{% extends "home_base.html" %}

{% block title %}Support Tickets{% endblock %}

{% block content %}

<div class="product-item">
    {% for ticket in support_tickets %}
        <h3>Title</h3>
        <p>{{ ticket.title }}</p>
        <h3>Description</h3>
        <p>{{ ticket.description }}</p>
        <h3>Status</h3>
        <p>{{ ticket.status }}</p>
        <p><br></p>
    {% endfor %}
</div>
{% endblock %}

orders/templates/orderitem_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Confirm Deletion</title>
</head>
<body>
    <h1>Are you sure you want to delete this item from your cart?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
        <a href="{% url 'orders:show_cart' %}">Cancel</a>
    </form>
</body>
</html>

orders/templates/show_cart.html
{% extends "home_base.html" %}

{% block title %}Cart{% endblock %}

{% block content %}

<div class="product-item">
    {% for item in order.items.all %}
        <img src="{{ item.product.image_url }}" alt="{{ item.product.name }}">
        <h3>{{ item.product.name }}</h3>
        <p>Rs {{ item.product.price }}</p>
        <p>{{ item.quantity }}</p>
        <p>Rs {{ item.price }}</p>
        <div>
            <a href="{% url "orders:delete_product_from_cart" item.id %}">Delete</a>
        </div>
    {% endfor %}
</div>
<div>
    <h1>{{ order.total_price }}</h1>
</div>
<div>
    <a href="{% url "orders:show_ticket_form" order.id %}">Make a Support Ticket</a>
</div>
<div>
        <form method="post" action="{% url 'orders:finalize_order' order.id %}">
            {% csrf_token %}
            <button type="submit">Finalize Order</button>
        </form>
</div>
{% endblock %}

orders/templates/show_orders.html
{% extends "home_base.html" %}

{% block title %}Order{% endblock %}

{% block content %}

<div class="product-item">
    {% for order in orders %}
        <h3>Order # {{ order.id }}</h3>
        {% for item in order.items.all %}
            <h3>{{ item.product.name }}</h3>
            <p>Rs {{ item.product.price }}</p>
            <p>{{ item.quantity }}</p>
            <p>Rs {{ item.price }}</p>
        {% endfor %}
    {% endfor %}
</div>

<div>
    <h1>{{ orders.total_price }}</h1>
</div>

{% endblock %}

orders/templates/show_support_tickets.html
{% extends "home_base.html" %}

{% block title %}Support Tickets{% endblock %}

{% block content %}

<div class="product-item">
    {% for ticket in support_tickets %}
        <h3>Subject</h3>
        <p>{{ ticket.subject }}</p>
        <h3>Description</h3>
        <p>{{ ticket.description }}</p>
        <h3>Status</h3>
        <p>{{ ticket.status }}</p>
        <p><br></p>
    {% endfor %}
</div>
{% endblock %}

orders/templates/support_ticket_form.html
{% extends "home_base.html" %}

{% block title %}Cart{% endblock %}

{% block content %}
<div>
    <form action="{% url "orders:create_support_ticket" order_id %}" method="post">
        {% csrf_token %}
        <div>
            <label for="subject">Subject:</label>
            <input type="text" id="subject" name="subject" maxlength="100" required>
        </div>
        <div>
            <label for="description">Description:</label>
            <textarea id="description" name="description" required></textarea>
        </div>
        <div>
            <button type="submit">Create Support Ticket</button>
        </div>
    </form>
</div>

{% endblock %}