orders/urls.py
from django.urls import path

from . import views
app_name = "orders"
urlpatterns = [
    path("add-to-cart/<int:product_id>/", views.AddToCart.as_view(), name="add_to_cart"),
    path("delete-from-cart/<int:pk>/", views.DeleteProductFromCart.as_view(), name="delete_product_from_cart"),
    path("create-support-ticket/<int:order_id>/", views.CreateSupportTicket.as_view(), name="create_support_ticket"),
    path("show-cart/", views.ShowCart.as_view(), name="show_cart"),
    path("show-orders/", views.ShowOrders.as_view(), name="show_orders"),
    path("show-ticket-form/<int:pk>/", views.ShowTicketForm.as_view(), name="show_ticket_form"),
    path("list-support-tickets/", views.ListSupportTickets.as_view(), name="list_support_tickets"),
    path("finalize-order/<int:order_id>", views.FinalizeOrder.as_view(), name="finalize_order"),
]

priceoyeclone/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from priceoyeclone import settings
from products.views import Homepage


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("users/", include("users.urls")),
                  path("api/user/", include("users.api.urls")),
                  path("api/order/", include("orders.api.urls")),
                  path("api/product/", include("products.api.urls")),
                  path("products/", include("products.urls")),
                  path("orders/", include("orders.urls", namespace="orders")),
                  path("sentry-debug/", trigger_error),
                  path("", Homepage.as_view()),
                  path("gettoken/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
                  path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
                  path("token/verify/", TokenVerifyView.as_view(), name="token_refresh"),
              ] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("review-for-product/list/<int:object_id>/", views.ProductReviewListingAPIView.as_view()),
    path("review-for-vendor/list/<int:object_id>/", views.VendorReviewListingAPIView.as_view()),
    path("list/", views.ProductListingAPIView.as_view()),
    path("add/", views.AddProductAPIView.as_view()),
    path("update/<int:pk>/", views.UpdateProductAPIView.as_view()),
    path("delete/<int:pk>/", views.DeleteProductAPIView.as_view()),
    path("add-vendor/", views.AddVendorAPIView.as_view()),
    path("update-vendor/<int:pk>/", views.UpdateVendorAPIView.as_view()),
    path("delete-vendor/<int:pk>/", views.DeleteVendorAPIView.as_view()),
    path("add-category/", views.AddCategoryAPIView.as_view()),
    path("update-category/<int:pk>/", views.UpdateCategoryAPIView.as_view()),
    path("delete-category/<int:pk>/", views.DeleteCategoryAPIView.as_view()),
]

products/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("homepage/", views.Homepage.as_view(), name="homepage"),
    path("<str:category_name>/", views.ProductListingByCategory.as_view(), name="product_listing_by_category"),
    path("<str:category_name>/<int:pk>", views.ProductDetailsView.as_view(), name="product_detail")
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password-reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete")
]

products/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel, ActivatorModel

from .managers import ProductManager, CategoryManager, VendorManager


class Category(TimeStampedModel, ActivatorModel):
    name = models.CharField(max_length=40, unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    objects = CategoryManager()

    def __str__(self):
        return self.name


class Vendor(TimeStampedModel, ActivatorModel):
    name = models.CharField(max_length=40, unique=True)

    objects = VendorManager()

    def __str__(self):
        return self.name


class SpecificationCategory(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Specification Categories"

    def __str__(self):
        return self.name


class ProductSpecificationCategory(models.Model):
    product = models.ForeignKey(
        "Product",
        on_delete=models.CASCADE,
        related_name="specification_categories"
    )
    specification_category = models.ForeignKey(
        SpecificationCategory,
        on_delete=models.CASCADE,
        related_name="product"
    )

    class Meta:
        verbose_name_plural = "Product Specification Categories"

    def __str__(self):
        return f"{self.product.name} - {self.specification_category.name}"


class SpecificationDetail(models.Model):
    specification_category = models.ForeignKey(
        ProductSpecificationCategory,
        on_delete=models.CASCADE,
        related_name="details")
    specification_label = models.CharField(max_length=100)
    specification_value = models.TextField()

    def __str__(self):
        return f"{self.specification_label}: {self.specification_value}"


class Product(TimeStampedModel, ActivatorModel):
    name = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image_url = models.URLField(max_length=200, blank=True, null=True)
    image = models.ImageField(null=True, blank=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True
    )
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True)

    objects = ProductManager()

    def __str__(self):
        return self.name

products/forms.py
from django import forms

from .models import Product, Category, Vendor


class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["vendor"].queryset = Vendor.objects.active()
        self.fields["category"].queryset = Category.objects.active()

    class Meta:
        model = Product
        exclude = ["deactivate_date"]

products/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import generics
from rest_framework.permissions import AllowAny, IsAuthenticated

from products.models import Product, Vendor, Category
from users.api.serializers import ReviewSerializer
from users.models import Review
from .filters import ProductFilter
from .permissions import IsStaff
from .serializers import AddProductSerializer, VendorSerializer, CategorySerializer, \
    ProductListingSerializer


class AllowAnyPermissionMixin:
    permission_classes = (AllowAny,)


class ProductReviewListingAPIView(AllowAnyPermissionMixin, generics.ListAPIView):
    serializer_class = ReviewSerializer

    def get_queryset(self):
        return Review.objects.get_active_reviews_for_model(Product, self.kwargs["object_id"])


class VendorReviewListingAPIView(AllowAnyPermissionMixin, generics.ListAPIView):
    serializer_class = ReviewSerializer

    def get_queryset(self):
        return Review.objects.get_active_reviews_for_model(Vendor, self.kwargs["object_id"])


class ProductListingAPIView(AllowAnyPermissionMixin, generics.ListAPIView):
    serializer_class = ProductListingSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_class = ProductFilter

    def get_queryset(self):
        return Product.objects.active()


class StaffPermissionMixin:
    permission_classes = (IsStaff, IsAuthenticated)


class AddProductAPIView(StaffPermissionMixin, generics.CreateAPIView):
    serializer_class = AddProductSerializer


class UpdateProductAPIView(StaffPermissionMixin, generics.UpdateAPIView):
    queryset = Product.objects.all()
    serializer_class = AddProductSerializer


class DeleteProductAPIView(StaffPermissionMixin, generics.DestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = AddProductSerializer


class AddVendorAPIView(StaffPermissionMixin, generics.CreateAPIView):
    serializer_class = VendorSerializer


class UpdateVendorAPIView(StaffPermissionMixin, generics.UpdateAPIView):
    queryset = Vendor.objects.all()
    serializer_class = VendorSerializer


class DeleteVendorAPIView(StaffPermissionMixin, generics.DestroyAPIView):
    queryset = Vendor.objects.all()
    serializer_class = VendorSerializer


class AddCategoryAPIView(StaffPermissionMixin, generics.CreateAPIView):
    serializer_class = CategorySerializer


class UpdateCategoryAPIView(StaffPermissionMixin, generics.UpdateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class DeleteCategoryAPIView(StaffPermissionMixin, generics.DestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

products/views.py
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.views.generic.list import ListView

from .models import Product, Category, Vendor, ProductSpecificationCategory


class ProductDetailsView(DetailView):
    model = Product
    template_name = "product_detail.html"
    context_object_name = "selected_product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["product_specification_categories"] = ProductSpecificationCategory.objects.filter(
            product=self.get_object())
        return context


class Homepage(ListView):
    model = Product
    template_name = "homepage.html"
    context_object_name = "products"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context


class ProductListingByCategory(ListView):
    model = Product
    template_name = "category_product_page.html"
    paginate_by = 10

    def __init__(self):
        super().__init__()
        self.selected_category = None
        self.selected_vendors = None

    def get_queryset(self):
        self.selected_category = get_object_or_404(Category, name=self.kwargs["category_name"])
        self.selected_vendors = self.request.GET.getlist("vendor")
        queryset = Product.objects.filter(category=self.selected_category)
        if self.selected_vendors:
            queryset = queryset.filter(vendor__in=self.selected_vendors)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["vendors"] = (Vendor.objects.filter(product__category=self.selected_category)
                              .annotate(lower_name=Lower("name"))
                              .order_by("lower_name").distinct())
        context["selected_vendors"] = self.selected_vendors
        return context

products/templates/category_product_page.html
{% extends 'home_base.html' %}

{% block title %}{{ categories.name }}{% endblock %}

{% block content %}
<form method="get" id="vendor-filter-form">
    <div>
        <h3>Filter by Vendor</h3>
        {% for vendor in vendors %}
            <label>
                <input type="checkbox" name="vendor" value="{{ vendor.id }}"
                       {% if vendor.id|stringformat:"s" in selected_vendors %}checked{% endif %}>
                {{ vendor.name }}
            </label>
        {% endfor %}
    </div>
    <button type="submit">Apply Filter</button>
</form>
<div class="product-grid">
    {% for product in page_obj %}
        <div class="product-item">
            <a href="{% url "product_detail" product.category product.id %}">
            <img src="{{ product.image_url }}" alt="{{ product.name }}">
            <h3>{{ product.name }}</h3>
                <p>Rs {{ product.price }}</p></a>
        </div>
    {% endfor %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1{% for vendor in selected_vendors %}&vendor={{ vendor }}{% endfor %}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}{% for vendor in selected_vendors %}&vendor={{ vendor }}{% endfor %}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% for vendor in selected_vendors %}&vendor={{ vendor }}{% endfor %}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}{% for vendor in selected_vendors %}&vendor={{ vendor }}{% endfor %}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

products/templates/home_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Homepage{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/homepage.css" %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        .content-wrapper {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <div class="left">
            <div class="dropdown">
                <span>Categories</span>
                <div class="dropdown-content">
                    {% for category in categories %}
                        <a href="{% url "product_listing_by_category" category.name %}">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="right">
            <div class="dropdown">
                <span>My Profile</span>
                <div class="dropdown-content">
                    <a href="{% url "profile" %}">My Profile</a>
                    <a href="{% url "homepage" %}">Homepage</a>
                    <a href="{% url "orders:show_cart" %}">Show Cart</a>
                    <a href="{% url "orders:list_support_tickets" %}">Show tickets</a>
                    <a href="{% url "orders:show_orders" %}">Show Orders</a>
                    <form id="logout-form" action="{% url "logout" %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="content-wrapper">
        {% block content %}
        {% endblock %}
    </div>

    <script>
        $(document).ready(function(){
            $(".dropdown").hover(function() {
                $(this).find(".dropdown-content").stop(true, true).slideDown("fast");
            }, function() {
                $(this).find(".dropdown-content").stop(true, true).slideUp("fast");
            });
        });
    </script>
</body>
</html>

products/templates/homepage.html
{% extends 'home_base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}
<div class="product-grid">
    {% for product in page_obj %}
        <div class="product-item">
            <img src="{{ product.image_url }}" alt="{{ product.name }}">
            <h3>{{ product.name }}</h3>
            <p>Rs {{ product.price }}</p>
        </div>
    {% endfor %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

products/templates/product_detail.html
{% extends "home_base.html" %}

{% block title %}{{ selected_product.name }}{% endblock %}

{% block content %}

<div class="product-item">
    <img src="{{ selected_product.image_url }}" alt="{{ selected_product.name }}">
    <h3>{{ selected_product.name }}</h3>
    <p>Rs {{ selected_product.price }}</p>
    <div class="cart-url">
        <a href="{% url "orders:add_to_cart" selected_product.id %}">ADD TO CART</a>
    </div>
</div>

{% for product_specification_category in product_specification_categories %}
    <div class="product-specs">
        <h3>{{ product_specification_category.specification_category }}</h3>
        {% for spec_details in product_specification_category.details.all %}
            <p>{{ spec_details }}</p>
        {% endfor %}
    </div>
{% endfor %}

{% endblock %}

products/templates/product_details.html
{% extends 'home_base.html' %}

{% block title %}{{ selected_product.name }}{% endblock %}

{% block content %}

<div class="product-item">
    <img src="{{ selected_product.image_url }}" alt="{{ selected_product.name }}">
    <h3>{{ selected_product.name }}</h3>
    <p>Rs {{ selected_product.price }}</p>
</div>

{% for category in spec_categories %}
    <div class="product-specs">
        <h3>{{ category }}</h3>
        {% for spec_details in product_specifications %}
            {% if spec_details.specification_category == category %}
                <p>{{ spec_details.specification_label }}:{{ spec_details.specification_value }}</p>
            {% endif %}
        {% endfor %}
    </div>
{% endfor %}

{% endblock %}